project:
  type: website

website:
  title: "Ajay Mahajan"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/ajay-mahajan-ai
      - icon: twitter
        href: https://twitter.com/
      - icon: search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

